### ISSUE TITLE
Daily cost calculation is not accurate

### ISSUE THREAD

**Issue by sebastianrasor** [thebradleysanders/evergy_home_assistant#5]
![image](https://user-images.githubusercontent.com/92653912/231648507-be6003dd-4ea5-49d5-acb4-a3007aef9aca.png)
I'm not sure what the internal logic is for the daily cost sensor, but it is overshooting the actual daily cost by a whole lot

**Comment by thebradleysanders** [comment]
Yes, I have seen the behavior also. The number is pulled right out of the unofficial API with no additional logic applied to it.
I will work on getting a more accurate number, whether generated or not. Thank you.

**A temp fix:** using the Energy Dashboard, manually set the cost/kwh, this number can be found on their website.

**Comment by tboyce021** [comment]
Apparently, I already did a bit of research on this back when I played around with it. See my comments here: https://github.com/lawrencefoley/evergy/issues/8#issuecomment-982189668

The TLDR is that `cost` = `usage` + `demand`, so I don't think it's really the dollar cost.

**Comment by thebradleysanders** [comment]
Sensor removed.
